--- drivers/net/ethernet/mellanox/mlx5/core/Makefile
+++ drivers/net/ethernet/mellanox/mlx5/core/Makefile
@@ -43,7 +43,7 @@
 # Core extra
 #
 mlx5_core-$(CONFIG_MLX5_ESWITCH)   += eswitch.o eswitch_offloads.o eswitch_offloads_termtbl.o \
-				      ecpf.o rdma.o esw/chains.o esw/acl_egress.o \
+				      ecpf.o rdma.o lib/chains.o esw/acl_egress.o \
 				      esw/acl_egress_lgcy.o esw/acl_egress_ofld.o
 mlx5_core-$(CONFIG_MLX5_MPFS)      += lib/mpfs.o
 mlx5_core-$(CONFIG_VXLAN)          += lib/vxlan.o
